# Generated by Django 3.0.5 on 2020-04-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='services',
        ),
        migrations.AddField(
            model_name='appointment',
            name='service_name',
            field=models.ManyToManyField(related_name='appointment', to='appointments.Services'),
        ),
    ]
