# Generated by Django 3.0.5 on 2020-04-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_remove_appointment_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name_plural': 'services'},
        ),
        migrations.AlterField(
            model_name='services',
            name='delivery_time',
            field=models.CharField(choices=[('B1', '1 Business Day'), ('B2', '2 Business Days'), ('BS', '2 - 3 Business Days'), ('B3', '3 Business Days'), ('B4', '4 Business Days'), ('B5', '5 Business Days'), ('B6', '6 Business Days'), ('B7', '7 Business Days')], default='B1', max_length=2),
        ),
    ]
